[package]
name = "pine"
version = "0.1.0"
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
pico-args = "0.4.2"
yansi = "0.5"
tini = "1.1"
chrono = "0.4"